spring.application.name=EggCounter

jwt.secretKey=asdasdlkjoewiruw32098403djsfj)(#)@)(JFSKJSOFJ#(*&

spring.datasource.url=jdbc:postgresql://ep-mute-queen-b3zyr7ik-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jHQ4xgYL6brN
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



#
#  user=
#
#  password=
#
#
#
#  channelBinding=require

#jdbc:postgresql://localhost:5432/eggCounter
