spring.application.name=EggCounter

jwt.secretKey=asdasdlkjoewiruw32098403djsfj)(#)@)(JFSKJSOFJ#(*&

spring.datasource.url=jdbc:postgresql://localhost:5432/eggCounter
spring.datasource.username=postgres
spring.datasource.password=reyansh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
